version: '3'
services:
  app:
    build: ./node
    container_name: portfolio-dev
    command: "npm run develop"
    ports:
      - 8000:8000
    volumes:
      - ./portfolio:/src
    working_dir: /src

